package ProblemSolving.Stacks;

import java.util.LinkedList;

public class RemoveKDigits {
    public String removeKdigits(String num, int k) {
        LinkedList<Character> stack = new LinkedList<>();

        for (Character character : num.toCharArray()) {
            while (stack.size() > 0 && k > 0 && character > stack.peekLast()) {
                stack.removeLast();
                k--;
            }
            stack.addLast(character);
        }

        for (int i = 0; i < k; i++) {
            stack.removeLast();
        }

        StringBuilder stringBuilder = new StringBuilder("");
        boolean leadingZero = true;

        for (Character character : stack) {
            if (leadingZero && character == '0') continue;

            stringBuilder.append(character);
            leadingZero = false;
        }

        return stringBuilder.toString();
    }

    public static void main(String[] args) {
        String string = "leet2";
        String s = "vzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppmvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppvzppm";
        System.out.println(s.substring(2918, 2919));
    }
}
